# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GasDataProcessor
                                 A QGIS plugin
 Processes and plots gas points from exported text file from Laser Methane Mini
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2019-04-21
        copyright            : (C) 2019 by Silver Spring Energy Consulting Ltd.
        email                : tpubben@silverspringenergy.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load GasDataProcessor class from file GasDataProcessor.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .methane_mini import GasDataProcessor
    return GasDataProcessor(iface)
