# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GasDataProcessor
                                 A QGIS plugin
 Processes and plots gas points from exported text file from Laser Methane Mini
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2019-04-21
        git sha              : $Format:%H$
        copyright            : (C) 2019 by Silver Spring Energy Consulting Ltd.
        email                : tpubben@silverspringenergy.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from PyQt5.QtCore import QSettings, QTranslator, qVersion, QCoreApplication, QVariant
from PyQt5.QtGui import QIcon
from PyQt5.QtWidgets import QAction, QFileDialog

# Initialize Qt resources from file resources.py
from .resources import *
# Import the code for the dialog
from .methane_mini_dialog import GasDataProcessorDialog
import os.path


# Import QGIS modules

from qgis.core import *


class GasDataProcessor:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'GasDataProcessor_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)

            if qVersion() > '4.3.3':
                QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&Gas data processor')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('GasDataProcessor', message)

    def add_action(
            self,
            icon_path,
            text,
            callback,
            enabled_flag=True,
            add_to_menu=True,
            add_to_toolbar=True,
            status_tip=None,
            whats_this=None,
            parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ':/plugins/methane_mini/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u'Gas Processor'),
            callback=self.run,
            parent=self.iface.mainWindow())

        # will be set False in run()
        self.first_start = True

    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&Gas data processor'),
                action)
            self.iface.removeToolBarIcon(action)

    def selectExportFiles(self):
        """Locates the text/csv files for import"""
        class_variables.export_filename, _filter = QFileDialog.getOpenFileNames(self.dlg, "Select Input Files", '',
                                                                               '*.csv *.txt')
        self.dlg.listWidget1.clear()
        try:
            self.dlg.listWidget1.addItem(class_variables.export_filename)
        except:
            self.dlg.listWidget1.addItems(class_variables.export_filename)

    def run(self):
        """Run method that performs all the real work"""

        # Create the dialog with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only load when the plugin is started
        if self.first_start == True:
            self.first_start = False
            self.dlg = GasDataProcessorDialog()
            self.dlg.openFileButton.clicked.connect(self.selectExportFiles)

        # show the dialog
        self.dlg.show()
        # Run the dialog event loop
        result = self.dlg.exec_()
        # See if OK was pressed
        if result:
            output_layer_name = self.dlg.outputLayerName.text() # pull the layer out of the input box

            # create the layer in memory
            gas_layer = QgsVectorLayer('Point', output_layer_name, 'memory')
            # set the CRS to ESPG 4326 WGS84
            gas_layer.setCrs(QgsCoordinateReferenceSystem(4326))
            pr = gas_layer.dataProvider()  # starts the data provider
            gas_layer.startEditing()
            pr.addAttributes([QgsField('GasReading', QVariant.Double)])  # creates a float field for gas readings

            # iterate through all files in the import box and add them as points to the layer
            for item in class_variables.export_filename:
                file = open(item)
                for line in file:
                    if line.startswith('n'):  # ignores the first line of the text output since it starts with "name"
                        continue
                    else:
                        sl = line.strip().split(',')  # strips newline and splits on comma
                        gas_reading, ycoord, xcoord = float(sl[0]), float(sl[1]), float(sl[2])

                    # add point feature for each reading
                    pnt = QgsFeature()
                    pnt.setGeometry(QgsGeometry.fromPointXY(QgsPointXY(xcoord,ycoord)))
                    pnt.setAttributes([gas_reading])
                    pr.addFeatures([pnt])

                    gas_layer.commitChanges()

            QgsProject.instance().addMapLayer(gas_layer)



class class_variables:
    export_filename = []
    output_filename = ''
